name: Compile and Test
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - uses: coq-community/docker-coq-action@v1
        with:
          coq_version: "latest"
          ocaml_version: "default"
          script: |
            startGroup "Build project"
              ls
              cd src
              make
            endGroupmake
